tasks:
  - init: npm install
    command: (sleep 2; gp preview $(gp url 8272)/test) & npm run debug
ports:
  - port: 8272
    visibility: public
    onOpen: ignore
  - port: 9229
    visibility: private
    onOpen: ignore
