/* helper functions generated by ChatGPT */

function positionElementsInArc(elements, radius, arcAngle, container) {
  const n = elements.length;
  const middleIndex = Math.floor(n / 2);

  for (let i = 0; i < n; i++) {
    const angle = (arcAngle / (n - 1)) * (i - middleIndex);
    const radians = (Math.PI / 180) * angle;
    const x = container.clientWidth / 2 + radius * Math.sin(radians) - elements[i].offsetWidth / 2;
    const y = container.clientHeight / 2 + (radius - elements[i].offsetHeight / 2) * (1 - Math.cos(radians));

    elements[i].style.position = 'absolute';
    elements[i].style.left = `${x}px`;
    elements[i].style.top = `${y-100}px`;
    elements[i].style.transform = `rotate(${angle}deg)`;
    elements[i].style.zIndex = (i === middleIndex ? n : n - Math.abs(i - middleIndex));
  }
}

function getBoundingClientRectWithAbsoluteChildren(element) {
  const rect = element.children.length ? { left: 9999, top: 9999, right: 0, bottom: 0 } : element.getBoundingClientRect();
  let left = rect.left;
  let top = rect.top;
  let right = rect.right;
  let bottom = rect.bottom;

  for(const child of element.children) {
    const childRect = child.getBoundingClientRect();
    left = Math.min(left, childRect.left);
    top = Math.min(top, childRect.top);
    right = Math.max(right, childRect.right);
    bottom = Math.max(bottom, childRect.bottom);
  }

  return {
    left,
    top,
    right,
    bottom,
    width: right - left,
    height: bottom - top
  };
}

function centerElementInClientRect(element, boundingClientRect) {
  const elementRect = getBoundingClientRectWithAbsoluteChildren(element);

  const centerX = boundingClientRect.left + boundingClientRect.width / 2;
  const centerY = boundingClientRect.top + boundingClientRect.height / 2;

  const elementCenterX = elementRect.left + elementRect.width / 2;
  const elementCenterY = elementRect.top + elementRect.height / 2;

  const translateX = centerX - elementCenterX;
  const translateY = centerY - elementCenterY;

  element.style.transform = `translate(${translateX}px, ${translateY}px) ${element.style.transform}`;
}

function parseRankRange(rankRange) {
  const rankArray = [];
  const rankElements = rankRange.split(',');

  rankElements.forEach(rankElement => {
    if(rankElement.match(/-?[0-9]+--?[0-9]+/)) {
      const [start, end] = rankElement.split('-').map(Number);
      for(let i = start; i <= end; i++)
        rankArray.push(i);
    } else {
      rankArray.push(rankElement);
    }
  });

  return rankArray;
}

async function setCardCount(deck, cardType, count) {
    batchStart();
    setDeltaCause(`${getPlayerDetails().playerName} updated card count of deck ${deck.id} (card type ${cardType}) in editor`);
    // Get the current cards of the specific cardType in the deck
    const currentCards = widgetFilter(w => w.get('deck') == deck.id && w.get('cardType') == cardType);
    const currentCount = currentCards.length;

    if (count < currentCount) {
        // If the desired count is less than the current count, remove cards
        for (let i = 0; i < currentCount - count; i++) {
            await removeWidgetLocal(currentCards[i].get('id'));
        }
    } else if (count > currentCount) {
        // If the desired count is greater than the current count, add cards
        for (let i = 0; i < count - currentCount; i++) {
            const card = { deck: deck.id, type: 'card', cardType: cardType };
            await addWidgetLocal(card);

            if (deck.get('parent')) {
                await widgets.get(card.id).moveToHolder(widgets.get(deck.get('parent')));
            } else {
                await widgets.get(card.id).updatePiles();
            }
        }
    }
    batchEnd();
}

/* end helper functions */


// Which properties make up the "appearance" of each widget type and which
// inputs edit its type specific behavior. Each entry becomes an input created
// by renderInputs; "cssKey" entries edit one declaration inside the css
// property instead of a whole widget property.
const editorTypeSections = {
  basic: {
    appearance: [
      { label: 'Color',         property: 'color',        kind: 'color' },
      { label: 'Image',         property: 'image',        kind: 'image' },
      { label: 'Icon',          property: 'icon',         kind: 'icon' },
      { label: 'Text',          property: 'text',         kind: 'text', nullIfEmpty: true },
      { label: 'Border radius', property: 'borderRadius', kind: 'number', min: 0, max: 200, slider: true, nullIfEmpty: true }
    ]
  },
  button: {
    appearance: [
      { label: 'Text',             property: 'text',              kind: 'text', nullIfEmpty: true },
      { label: 'Icon',             property: 'icon',              kind: 'icon' },
      { label: 'Image',            property: 'image',             kind: 'image' },
      { label: 'Text color',       property: 'textColor',         kind: 'color' },
      { label: 'Background',       property: 'backgroundColor',   kind: 'color' },
      { label: 'Border',           property: 'borderColor',       kind: 'color' },
      { label: 'Text (hover)',     property: 'textColorOH',       kind: 'color' },
      { label: 'Background (hover)', property: 'backgroundColorOH', kind: 'color' },
      { label: 'Border (hover)',   property: 'borderColorOH',     kind: 'color' },
      { label: 'SVG color',        property: 'color',             kind: 'color' },
      { label: 'Border radius',    property: 'borderRadius',      kind: 'number', min: 0, max: 800, slider: true }
    ]
  },
  canvas: {
    behavior: [
      { label: 'Resolution',   property: 'resolution',  kind: 'number', min: 10, max: 1000 },
      { label: 'Line width',   property: 'lineWidth',   kind: 'number', min: 1, max: 10, slider: true },
      { label: 'Active color', property: 'activeColor', kind: 'number', min: 0, max: 9, slider: true }
    ]
  },
  dice: {
    appearance: [
      { label: 'Face color',    property: 'color',        kind: 'color' },
      { label: 'Pip color',     property: 'pipColor',     kind: 'color' },
      { label: 'Border color',  property: 'borderColor',  kind: 'color' },
      { label: 'Icon',          property: 'icon',         kind: 'icon' },
      { label: 'Image',         property: 'image',        kind: 'image' },
      { label: 'Border radius', property: 'borderRadius', kind: 'text', placeholder: 'e.g. 16%', nullIfEmpty: true }
    ],
    behavior: [
      { label: 'Roll time (ms)', property: 'rollTime', kind: 'number', min: 0, max: 5000 },
      { label: 'Swap time (ms)', property: 'swapTime', kind: 'number', min: 0, max: 5000 }
    ]
  },
  holder: {
    appearance: [
      { label: 'Color',         property: 'color',        kind: 'color' },
      { label: 'Text color',    property: 'textColor',    kind: 'color' },
      { label: 'Border radius', property: 'borderRadius', kind: 'number', min: 0, max: 100, slider: true },
      { label: 'Drop shadow',   property: 'dropShadow',   kind: 'checkbox' }
    ],
    behavior: [
      { label: 'Align dropped widgets', property: 'alignChildren',    kind: 'checkbox' },
      { label: 'Prevent piles',         property: 'preventPiles',     kind: 'checkbox' },
      { label: 'Children per owner',    property: 'childrenPerOwner', kind: 'checkbox' },
      { label: 'Drop offset X',         property: 'dropOffsetX',      kind: 'number' },
      { label: 'Drop offset Y',         property: 'dropOffsetY',      kind: 'number' },
      { label: 'Stack offset X',        property: 'stackOffsetX',     kind: 'number' },
      { label: 'Stack offset Y',        property: 'stackOffsetY',     kind: 'number' }
    ]
  },
  pile: {
    appearance: [
      { label: 'Handle text',     property: 'text',           kind: 'text', nullIfEmpty: true },
      { label: 'Handle position', property: 'handlePosition', kind: 'select', choices: [ 'top left', 'top', 'top right', 'right', 'bottom right', 'bottom', 'bottom left', 'left', 'static' ].map(v=>({ value: v, text: v })) },
      { label: 'Handle offset',   property: 'handleOffset',   kind: 'number', min: 0, max: 100, slider: true }
    ],
    behavior: [
      { label: 'Snap range', property: 'pileSnapRange', kind: 'number', min: 0, max: 200, slider: true }
    ]
  },
  scoreboard: {
    appearance: [
      { label: 'Border radius',      property: 'borderRadius',     kind: 'number', min: 0, max: 100, slider: true },
      { label: 'Player colors',      property: 'showPlayerColors', kind: 'checkbox' },
      { label: 'Vertical header',    property: 'verticalHeader',   kind: 'checkbox' },
      { label: 'Autosize columns',   property: 'autosizeColumns',  kind: 'checkbox' }
    ],
    behavior: [
      { label: 'Score property',     property: 'scoreProperty',    kind: 'text' },
      { label: 'Players in columns', property: 'playersInColumns', kind: 'checkbox' },
      { label: 'Show totals',        property: 'showTotals',       kind: 'checkbox' },
      { label: 'Show all rounds',    property: 'showAllRounds',    kind: 'checkbox' },
      { label: 'Show all seats',     property: 'showAllSeats',     kind: 'checkbox' },
      { label: 'Round label',        property: 'roundLabel',       kind: 'text' },
      { label: 'Totals label',       property: 'totalsLabel',      kind: 'text' },
      { label: 'Current round',      property: 'currentRound',     kind: 'number', nullIfEmpty: true },
      { label: 'Sort field',         property: 'sortField',        kind: 'text' },
      { label: 'Sort ascending',     property: 'sortAscending',    kind: 'checkbox' },
      { label: 'First column width', property: 'firstColWidth',    kind: 'number', min: 10, max: 500 },
      { label: 'Edit pane title',    property: 'editPaneTitle',    kind: 'text' }
    ]
  },
  seat: {
    appearance: [
      { label: 'Color',         property: 'color',        kind: 'color' },
      { label: 'Color (empty)', property: 'colorEmpty',   kind: 'color' },
      { label: 'Border radius', property: 'borderRadius', kind: 'number', min: 0, max: 100, slider: true }
    ],
    behavior: [
      { label: 'Seat index',        property: 'index',          kind: 'number', min: 1, max: 16 },
      { label: 'Display property',  property: 'display',        kind: 'text' },
      { label: 'Text when empty',   property: 'displayEmpty',   kind: 'text' },
      { label: 'Hand holder',       property: 'hand',           kind: 'text' },
      { label: 'Has the turn',      property: 'turn',           kind: 'checkbox' },
      { label: 'Skip turn',         property: 'skipTurn',       kind: 'checkbox' },
      { label: 'Hide turn marker',  property: 'hideTurn',       kind: 'checkbox' },
      { label: 'Hide when unused',  property: 'hideWhenUnused', kind: 'checkbox' }
    ]
  },
  spinner: {
    appearance: [
      { label: 'Text color',    property: 'textColor',    kind: 'color' },
      { label: 'Line color',    property: 'lineColor',    kind: 'color' },
      { label: 'Border radius', property: 'borderRadius', kind: 'text', placeholder: 'e.g. 50%', nullIfEmpty: true }
    ],
    behavior: [
      { label: 'Current value', property: 'value', kind: 'text' }
    ]
  },
  timer: {
    appearance: [
      { label: 'Background', cssKey: 'background', kind: 'color' },
      { label: 'Text color', cssKey: 'color',      kind: 'color' }
    ],
    behavior: [
      { label: 'Countdown',         property: 'countdown',    kind: 'checkbox' },
      { label: 'Paused',            property: 'paused',       kind: 'checkbox' },
      { label: 'Alert when done',   property: 'alert',        kind: 'checkbox' },
      { label: 'Precision',         property: 'precision',    kind: 'select', choices: [ { value: 1000, text: '1 second' }, { value: 100, text: '0.1 seconds' }, { value: 10, text: '0.01 seconds' }, { value: 1, text: '1 millisecond' } ] },
      { label: 'Start (ms)',        property: 'start',        kind: 'number' },
      { label: 'End (ms)',          property: 'end',          kind: 'number', nullIfEmpty: true },
      { label: 'Current time (ms)', property: 'milliseconds', kind: 'number' }
    ]
  }
};

const editorTypeNames = {
  basic: 'Widget',
  button: 'Button',
  canvas: 'Canvas',
  card: 'Card',
  deck: 'Deck',
  dice: 'Dice',
  holder: 'Holder',
  label: 'Label',
  pile: 'Pile',
  scoreboard: 'Scoreboard',
  seat: 'Seat',
  spinner: 'Spinner',
  timer: 'Timer'
};

class PropertiesModule extends SidebarModule {
  constructor() {
    super('tune', 'Properties', 'Edit widget properties.');
    this.widgetPick = null;
  }

  // --- widget picking (used by the appearance pipette) ---

  startWidgetPick(targetWidget, callback) {
    this.widgetPick = { targetID: targetWidget.id, callback };
    $('body').classList.add('editorWidgetPicking');
  }

  stopWidgetPick() {
    this.widgetPick = null;
    $('body').classList.remove('editorWidgetPicking');
  }

  addInput(labelText, value, onValueChanged, target, type='auto') {
    const id = 'genericInput' + rand().toString(36).substring(3, 12);
    let currentValue = null;
    let inputDOM = null;

    const wrapperDOM = div(target || this.moduleDOM, 'genericInput', `
      <label for=${id} style="display:inline-block;width:100px">${html(labelText)}</label>
      <select>
        <option>not set</option>
        <option>text</option>
        <option>number</option>
        <option>NULL</option>
        <option>false</option>
        <option>true</option>
        <option>object/array</option>
      </select>
    `);

    const setType = function(t) {
      $('select', wrapperDOM).value = t;
      if(t == 'object/array' && (!inputDOM || inputDOM.tagName != 'TEXTAREA')) {
        if(inputDOM)
          inputDOM.remove();
        inputDOM = document.createElement('textarea');
        inputDOM.id = id;
        wrapperDOM.appendChild(inputDOM);
        inputDOM.onkeyup = inputDOM.oninput = inputDOM.onchange = e=>{
          try {
            const newValue = JSON.parse(inputDOM.value);
            setValue(newValue, true);
            inputDOM.classList.remove('inputError');
          } catch(e) {
            inputDOM.classList.add('inputError');
          }
        };
      } else if(t == 'text' || t == 'number') {
        if(!inputDOM || inputDOM.tagName != 'INPUT') {
          if(inputDOM)
            inputDOM.remove();
          inputDOM = document.createElement('input');
          inputDOM.id = id;
          wrapperDOM.appendChild(inputDOM);
        }
        inputDOM.type = t;
        if(t == 'number')
          inputDOM.step = 'any';
        inputDOM.onkeyup = inputDOM.oninput = inputDOM.onchange = _=>{
          if(inputDOM) // it might have been removed by another event
            setValue(t=='number'?+inputDOM.value||0:inputDOM.value, true);
        };
      } else if(t != 'object/array') {
        if(inputDOM)
          inputDOM.remove();
        inputDOM = null;
      }
    };

    const setValue = function(v, triggerCallback=false) {
      const json = typeof v === 'undefined' ? undefined : JSON.stringify(v, null, '  ');
      if(json !== currentValue) {
        currentValue = json;
        if(typeof v === 'undefined')
          setType('not set');
        else if(typeof v === 'string')
          setType('text');
        else if(typeof v === 'number')
          setType('number');
        else if(v === null)
          setType('NULL');
        else if(v === true)
          setType('true');
        else if(v === false)
          setType('false');
        else if(typeof v === 'object')
          setType('object/array');

        if(typeof v === 'string' || typeof v === 'number')
          inputDOM.value = v;
        if(typeof v === 'object' && v !== null)
          inputDOM.value = json;

        if(triggerCallback)
          onValueChanged(v);
      }
    };

    const getValue = _=>typeof currentValue === 'undefined' ? undefined : JSON.parse(currentValue);

    setValue(value);

    $('select', wrapperDOM).onchange = _=>{
      switch($('select', wrapperDOM).value) {
        case 'not set':
          setValue(undefined, true); break;
        case 'text':
          setValue(String(getValue()||""), true); break;
        case 'number':
          setValue(+String(getValue())||0, true); break;
        case 'NULL':
          setValue(null, true); break;
        case 'false':
          setValue(false, true); break;
        case 'true':
          setValue(true, true); break;
        case 'object/array':
          setValue({}, true); break;
      }
    };

    return {
      dom: wrapperDOM,
      setValue,
      getValue
    };
  }

  addDeltaListener(updater) {
    this.globalInputUpdaters.push(updater);
  }

  addPropertyListener(widget, property, updater) {
    updater(widget);

    if(!this.inputUpdaters[widget.id])
      this.inputUpdaters[widget.id] = {};
    if(!this.inputUpdaters[widget.id][property])
      this.inputUpdaters[widget.id][property] = [];

    this.inputUpdaters[widget.id][property].push(v=>updater(widget));
  }

  inputValueUpdated(widget, property, value) {
    widget.set(property, typeof value === 'undefined' ? null : value);
  }

  onDeltaReceivedWhileActive(delta) {
    for(const widgetID in delta.s)
      if(delta.s[widgetID] && this.inputUpdaters[widgetID])
        for(const property in delta.s[widgetID])
          if(this.inputUpdaters[widgetID][property])
            for(const updater of this.inputUpdaters[widgetID][property])
              updater(delta.s[widgetID][property]);
    for(const updater of this.globalInputUpdaters)
      updater(delta.s);
  }

  onSelectionChangedWhileActive(newSelection) {
    if(this.widgetPick) {
      const pick = this.widgetPick;
      const target = widgets.get(pick.targetID);
      this.stopWidgetPick();
      if(target) {
        const picked = newSelection.filter(w=>w.id != pick.targetID)[0];
        if(picked)
          pick.callback(picked);
        setSelection([ target ]);
        return;
      }
    }

    this.moduleDOM.innerHTML = '';
    this.inputUpdaters = {};
    this.globalInputUpdaters = [];

    for(const widget of newSelection) {
      this.inputUpdaters[widget.id] = {};

      switch(widget.get('type')) {
        case 'button':     this.renderForButton(widget);     break;
        case 'canvas':     this.renderForCanvas(widget);     break;
        case 'card':       this.renderForCard(widget);       break;
        case 'deck':       this.renderForDeck(widget);       break;
        case 'dice':       this.renderForDice(widget);       break;
        case 'holder':     this.renderForHolder(widget);     break;
        case 'label':      this.renderForLabel(widget);      break;
        case 'pile':       this.renderForPile(widget);       break;
        case 'scoreboard': this.renderForScoreboard(widget); break;
        case 'seat':       this.renderForSeat(widget);       break;
        case 'spinner':    this.renderForSpinner(widget);    break;
        case 'timer':      this.renderForTimer(widget);      break;

        default:
          this.renderForBasic(widget);
          break;
      }
    }

    if(!newSelection.length)
      this.addDeck();
  }

  addDeck() {
    this.addHeader('Add deck');

    function createRadioButtons(target, name, options, callback) {
      let html = '';
      Object.keys(options).forEach((key, index) => {
        const option = options[key];
        html += `
          <div>
            <input type="radio" id="${name}${index}" name="${name}" value="${key}">
            <label for="${name}${index}"><strong>${option.header}</strong><div>${option.description}</div></label>
          </div>
        `;
      });

      const radioButtonsHTML = `<div class=headerRadioButtons>${html}</div>`;
      const container = document.createElement('div');
      container.innerHTML = radioButtonsHTML;
      target.append(container);

      Object.keys(options).forEach((_, index) => {
        const radioButton = container.querySelector(`#${name}${index}`);
        radioButton.addEventListener('change', (event) => {
          callback(event.target.value);
        });
      });

      return container;
    }

    createRadioButtons(this.moduleDOM, 'deckType', {
      custom: {
        header: 'Custom deck of cards',
        description: 'Generate a deck by defining suits (symbols and colors) and ranks for each suit'
      },
      images: {
        header: 'Upload one image per card or tiled images with multiple cards',
        description: 'Generate a deck by uploading images that cover the whole card. You may need to remove gaps or margins for tiled images in an image editor.'
      }
    }, v=>{
      options.innerHTML = '';
      if(v == 'custom')
        this.deckGenerator(options);
      if(v == 'images')
      this.deckImages(options);
    });

    const options = div(this.moduleDOM);
  }

  deckGenerator(target) {
    const deckTemplates = [ this.deckTemplate_standard, this.deckTemplate_colors, this.deckTemplate_simple, this.deckTemplate_skinny, this.deckTemplate_transparent ];

    const defaultRanks = [ 'skoll/diamonds', 'skoll/hearts', 'skoll/clubs', 'skoll/spades' ];

    const suitDivs = {};
    const colors = {};
    const ranks = {};

    this.addSubHeader('Suit symbols', target);

    const suitCustomizeDiv = document.createElement('div');
    this.addSubHeader('Suit properties', suitCustomizeDiv);

    const linkedRanksToggleDiv = document.createElement('div');
    const linkedRanksLabel = document.createElement('label');
    linkedRanksLabel.textContent = 'Same ranks for each suit:';
    const linkedRanksToggle = document.createElement('input');
    linkedRanksToggle.type = 'checkbox';
    linkedRanksToggle.checked = true;
    linkedRanksLabel.htmlFor = linkedRanksToggle.id = 'sameRanksToggle';

    linkedRanksToggleDiv.appendChild(linkedRanksLabel);
    linkedRanksToggleDiv.appendChild(linkedRanksToggle);
    suitCustomizeDiv.append(linkedRanksToggleDiv);

    const updateLinkedRanks = (symbol, newRanks) => {
      for(const otherSymbol in ranks)
        if(linkedRanksToggle.checked && otherSymbol !== symbol)
          $('.ranks input', suitDivs[otherSymbol]).value = ranks[otherSymbol] = newRanks;
    };
    const designSelectionDiv = document.createElement('div');
    const updateDesignPreview = _=>{
      const oldScrollTop = this.moduleDOM.scrollTop;
      const oldSelectedButton = $('.selected.deckTemplateButton', target);
      const oldSelectedButtonIndex = oldSelectedButton ? oldSelectedButton.dataset.index : -1;
      for(const button of $a('.deckTemplateButton', target))
        button.remove();

      if(Object.keys(colors).length == 0) {
        createButton.disabled = true;
        return;
      }

      const deck = getDeckDefinition(true);
      for(const [ index, deckTemplate ] of Object.entries(deckTemplates)) {
        const templateButton = this.renderWidgetButton(new Deck(deck.id), deckTemplate(deck), designSelectionDiv);
        templateButton.classList.add('deckTemplateButton');
        templateButton.dataset.index = index;
        templateButton.classList.toggle('selected', oldSelectedButtonIndex == index);
        templateButton.onclick = e=>{
          for(const button of $a('.deckTemplateButton', target))
            if(button != templateButton)
              button.classList.remove('selected');
          templateButton.classList.toggle('selected');
          createButton.disabled = !$a('.selected.deckTemplateButton', target).length;
        };
        deck.id = generateUniqueWidgetID();
      }
      this.moduleDOM.scrollTop = oldScrollTop;
    };

    for(const symbol of [ 'skoll/diamonds', 'skoll/hearts', 'skoll/clubs', 'skoll/spades', 'delapouite/round-star', 'delapouite/flower-emblem', 'delapouite/plain-circle', 'lorc/biohazard', 'lorc/fluffy-trefoil' ]) {
      const symbolButton = this.renderWidgetButton(new BasicWidget(), {
        image: `/i/game-icons.net/${symbol}.svg`,
        color: '#000',
        svgReplaces: { '#000': 'color' }
      }, target);
      symbolButton.dataset.symbol = symbol;
      symbolButton.classList.add('deckGeneratorSymbol');
      symbolButton.onclick = async e=>{
        symbolButton.classList.toggle('selected');
        if(symbolButton.classList.contains('selected')) {
          colors[symbol] = [ 'skoll/diamonds', 'skoll/hearts' ].includes(symbol) ? '#e50932' : '#000000';
          ranks[symbol] = '2-10,J,Q,K,A';

          suitDivs[symbol] = document.createElement('div');
          suitDivs[symbol].classList.add('suitProperties');
          const suitWidget = new BasicWidget();
          this.renderWidgetButton(suitWidget, {
            image: `/i/game-icons.net/${symbol}.svg`,
            color: colors[symbol],
            svgReplaces: { '#000': 'color' }
          }, suitDivs[symbol]);

          const colorPickerDiv = document.createElement('div');
          const colorPickerLabel = document.createElement('label');
          colorPickerLabel.textContent = 'Color:';
          const colorPicker = document.createElement('input');
          colorPicker.type = 'color';
          colorPicker.value = colors[symbol];
          colorPicker.onchange = e=>{
            colors[symbol] = colorPicker.value;
            suitWidget.applyDelta({ color: colorPicker.value });
            updateDesignPreview();
          };
          colorPickerDiv.appendChild(colorPickerLabel);
          colorPickerDiv.appendChild(colorPicker);
          suitDivs[symbol].append(colorPickerDiv);

          const rankInputDiv = document.createElement('div');
          const rankInputLabel = document.createElement('label');
          rankInputDiv.classList.add('ranks');
          rankInputLabel.textContent = 'Ranks:';
          const rankInput = document.createElement('input');
          rankInput.value = ranks[symbol];

          rankInput.onkeyup = e => {
            updateLinkedRanks(symbol, ranks[symbol] = rankInput.value);
            updateDesignPreview();
          };

          rankInputDiv.appendChild(rankInputLabel);
          rankInputDiv.appendChild(rankInput);
          suitDivs[symbol].append(rankInputDiv);

          suitCustomizeDiv.append(suitDivs[symbol]);
        } else {
          suitDivs[symbol].remove();
          delete suitDivs[symbol];
          delete colors[symbol];
          delete ranks[symbol];
        }
        updateDesignPreview();
      };

      if(defaultRanks.includes(symbol))
        symbolButton.click();
    }
    target.append(suitCustomizeDiv);

    function getDeckDefinition(standardDeck) {
      const id = generateUniqueWidgetID();
      const cardTypes = {};
      let suitIndex = 0;

      for(const [ suitSymbol, suitColor ] of Object.entries(colors)) {
        const suitURL = suitSymbol;
        for(const rank of parseRankRange(ranks[suitSymbol])) {
          const cT = `${rank} of ${suitSymbol.replace(/.*\//, '')}`;
          cardTypes[cT] = {
            suit: suitURL,
            suitColor,
            rank
          };
          const setCardTypes = (conditions, cardTypesKeys) => {
            if(conditions)
              for(const key of cardTypesKeys)
                if(standardDeck)
                  cardTypes[cT][`suit-${key}`] = suitURL;
          };
          if(String(rank).match(/^[0-9]+$/) && rank <= 21) {
            setCardTypes(rank     >=  4,                           ['P11', 'P13', 'P51', 'P53']);
            setCardTypes(rank     >= 12 || rank == 2 || rank == 3, ['P12', 'P52']);
            setCardTypes(rank     ==  7 || rank == 8,              ['P22']);
            setCardTypes(rank     >= 16 || rank >= 6 && rank <= 8, ['P31', 'P33']);
            setCardTypes(rank % 2 ==  1 && rank != 7,              ['P32']);
            setCardTypes(rank     ==  8,                           ['P42']);

            setCardTypes(rank >= 9,                                                          ['S21', 'S23', 'S31', 'S33']);
            setCardTypes(rank >= 20 || rank == 10 || rank == 11 || rank >= 14 && rank <= 17, ['S12', 'S42']);
            setCardTypes(rank >= 12,                                                         ['S22', 'S32']);
            setCardTypes(rank >= 18,                                                         ['S11', 'S13', 'S41', 'S43']);
          }
          if('JQK'.includes(rank)) {
            let defaultRanksuit = defaultRanks[suitIndex % 4].substr(6, 1).toUpperCase();
            if(defaultRanks.includes(suitSymbol))
              defaultRanksuit = suitSymbol.substr(6, 1).toUpperCase();
            cardTypes[cT].rankImage = `/i/cards-default/${rank}${defaultRanksuit}-face.svg`;
          } else if(!String(rank).match(/^[0-9]+$/) || rank > 21) {
            cardTypes[cT].rankImage = `/i/game-icons.net/${suitSymbol}.svg`;
          }
        }
        suitIndex += 1;
      }

      return {
        type: 'deck',
        id,
        cardTypes
      };
    }

    const createButton = document.createElement('button');
    createButton.innerText = 'Add to game';
    createButton.className = 'green';
    createButton.disabled = true;
    createButton.setAttribute('icon', 'add');
    createButton.onclick = async e=>{
      let standardDeck = false;
      const deckTemplateButton = document.querySelectorAll('.deckTemplateButton')[0];
      if (deckTemplateButton && deckTemplateButton.classList.contains('selected'))
        standardDeck = true
      batchStart();
      const deck = getDeckDefinition(standardDeck);
      setDeltaCause(`${getPlayerDetails().playerName} added custom deck "${deck.id}" in editor`);
      await addWidgetLocal(deckTemplates[$('.selected.deckTemplateButton', target).dataset.index](deck));

      let suitIndex = 0;
      for(const [ suitSymbol, suitColor ] of Object.entries(colors)) {
        let x = 0;
        for(const rank of parseRankRange(ranks[suitSymbol])) {
          const cT = `${rank} of ${suitSymbol.replace(/.*\//, '')}`;
          await addWidgetLocal({
            type: 'card',
            id: `${deck.id} ${cT}`,
            deck: deck.id,
            cardType: cT,
            x,
            y: suitIndex * 160,
            activeFace: 1
          });
          x += 103;
        }
        suitIndex += 1;
      }

      batchEnd();
    };

    target.append(suitCustomizeDiv);

    this.addSubHeader('Card design', target);
    target.append(designSelectionDiv);
    updateDesignPreview();
    target.append(createButton);
  }

  deckImages(target) {
    this.addSubHeader('Card backs', target);
    let backImageURL = '/i/cards-default/2B.svg';
    const backButtons = div(target);

    const addBackImageButton = image=>{
      this.renderWidgetButton(new BasicWidget(), { image }, backButtons).onclick = e=>{
        for(const button of $a('.widgetSelectionButton', backButtons))
          if(button != e.currentTarget)
            button.classList.remove('selected');
        e.currentTarget.classList.add('selected');
        backImageURL = image;
      };
      if(backImageURL == image)
        $('.widgetSelectionButton:last-child', backButtons).click();
    };
    for(const image of [ '/i/cards-default/1B.svg', '/i/cards-default/2B.svg', '/i/cards-default/3B.svg', '/i/cards-plastic/1B.svg', '/i/cards-plastic/2B.svg' ])
      addBackImageButton(image);

    div(target, 'buttonBar', `
      <button icon=upload id=backButton>Upload back...</button>
    `);

    $('#backButton').onclick = _=>uploadAsset(function(imagePath, fileName) {
      addBackImageButton(imagePath);
      $('.widgetSelectionButton:last-child', backButtons).click();
    });

    this.addSubHeader('Card fronts', target);
    const preview = div(target);

    div(target, 'goButton buttonBar', `
      <button icon=upload id=frontsButton>Upload fronts...</button>
      <button icon=add class=green disabled>Add to game</button>
    `);

    $('#frontsButton').onclick = _=>uploadAsset(async function(imagePath, fileName) {
      const dom = div(preview, 'cardFrontPreview', `
        <img src="${mapAssetURLs(imagePath)}">
        <div class=flexCenter>
          <div>
            <div class=rows>Rows (if multiple cards):<br><input type=range value=1 max=10> <input type=number value=1 min=0></div>
            <div class=cols>Cols (if multiple cards):<br><input type=range value=1 max=10> <input type=number value=1 min=0></div>
            <div class=cards>Cards to add:<br><input type=range value=1 max=10> <input type=number value=1 min=0></div>
            <button icon=delete>Delete</button>
          </div>
        </div>
      `);
      dom.dataset.imagePath = imagePath;
      dom.dataset.fileName = fileName;
      for(const name of [ 'rows', 'cols', 'cards' ]) {
        $(`.${name} [type=range]`, dom).oninput = e=>$(`.${name} [type=number]`, dom).value=e.target.value;
        $(`.${name} [type=number]`, dom).oninput = e=>$(`.${name} [type=range]`, dom).value=e.target.value;
      }
      $('[icon=delete]', dom).onclick = e=>dom.remove();
      $('.goButton [icon=add]', target).disabled = false;
    });

    $('.goButton [icon=add]', target).onclick = async _=>{
      const id = generateUniqueWidgetID();
      const cardTypes = {};
      const counts = {};
      const hasTiledImage = [...$a('.rows input, .cols input')].filter(d=>d.value>1).length > 0;
      for(const previewDiv of $a('.cardFrontPreview', preview)) {
        const rows = $('.rows input', previewDiv).value;
        const cols = $('.cols input', previewDiv).value;
        if(hasTiledImage) {
          for(let i=0; i<rows; ++i) {
            for(let j=0; j<cols; ++j) {
              const cardType = `${previewDiv.dataset.fileName} ${i},${j}`;
              cardTypes[cardType] = {
                image: previewDiv.dataset.imagePath,
                offsetX: j,
                offsetY: i,
                deckWidth: cols,
                deckHeight: rows
              };
              counts[cardType] = $('.cards input', previewDiv).value;
            }
          }
        } else {
          cardTypes[previewDiv.dataset.fileName] = {
            image: previewDiv.dataset.imagePath
          };
          counts[previewDiv.dataset.fileName] = $('.cards input', previewDiv).value;
        }
      }

      const deck = {
        id,
        type: 'deck',
        cardTypes,
        faceTemplates: [
          {
            "objects": [
              {
                "type": "image",
                "color": "transparent",
                "value": backImageURL,
                "dynamicProperties": {
                  "height": "height",
                  "width": "width"
                }
              }
            ]
          },
          {
            "objects": [
              {
                "type": "image",
                "color": "transparent",
                "dynamicProperties": {
                  "value": "image",
                  "height": "height",
                  "width": "width"
                }
              }
            ]
          }
        ]
      };

      let cardWidth = Math.round($('.cardFrontPreview img', preview).width / $('.cardFrontPreview img', preview).height * 160);
      if(hasTiledImage)
        cardWidth *= $('.rows input', preview).value / $('.cols input', preview).value;
      if(cardWidth != 103)
        deck.cardDefaults = { width: cardWidth };

      if(hasTiledImage) {
        deck.faceTemplates[1].objects[0].css = {
          "background-size": "calc(var(--width) * var(--deckWidth) * 1px) calc(var(--height) * var(--deckHeight) * 1px)",
          "background-position": "calc(var(--width) * var(--offsetX) * -1px) calc(var(--height) * var(--offsetY) * -1px)"
        };
        deck.cardDefaults.css = {
          '--offsetX':    '${PROPERTY offsetX}',
          '--offsetY':    '${PROPERTY offsetY}',
          '--deckWidth':  '${PROPERTY deckWidth}',
          '--deckHeight': '${PROPERTY deckHeight}',
          '--width':      '${PROPERTY width}',
          '--height':     '${PROPERTY height}'
        }
      }

      await this.addDeckWithCards(deck, 'image', counts);
    };
  }

  async addDeckWithCards(deck, type, counts) {
    batchStart();
    setDeltaCause(`${getPlayerDetails().playerName} added ${type} deck "${deck.id}" in editor`);
    await addWidgetLocal(deck);

    const cardWidth = deck.cardDefaults && deck.cardDefaults.width || 103;
    let x = 0;
    let y = 0;
    for(const cardType in deck.cardTypes) {
      const count = counts ? counts[cardType] || 0 : 1;
      for(let i=1; i<=count; ++i) {
        await addWidgetLocal({
          type: 'card',
          id: `${deck.id} ${cardType}${count > 1 ? ' '+i : ''}`,
          deck: deck.id,
          cardType: cardType,
          x,
          y: y * 160,
          activeFace: 1
        });
        x += cardWidth;
        if(x+cardWidth > 1600) {
          y += 1;
          x = 0;
        }
      }
    }

    batchEnd();
  }

  deckTemplate_colors(deck) {
    deck.cardDefaults = {
    };
    deck.faceTemplates = [
      {
        "radius": 10,
        "objects": [
          {
            "type": "image",
            "width": 103,
            "height": 160,
            "color": "#fff"
          },
          {
            "type": "image",
            "x": 5,
            "y": 5,
            "width": 93,
            "height": 150,
            "css": "border-radius:10px; background: linear-gradient(90deg, rgba(213,94,0,1) 14.3%, rgba(230,159,0,1) 14.4%, rgba(230,159,0,1) 28.6%, rgba(240,228,66,1) 28.7%, rgba(240,228,66,1) 42.8%, rgba(0,158,155,1) 42.9%, rgba(0,141,164,1) 57.1%, rgba(0,114,178,1) 57.2%, rgba(0,114,178,1) 71.4%, rgba(86,180,233,1) 71.5%, rgba(86,180,233,1) 85.7%, rgba(204,121,167,1) 85.8%, rgba(204,121,167,1) 100%);"
          }
        ],
        "border": 1
      },
      {
        "radius": 10,
        "objects": [
          {
            "type": "image",
            "width": 103,
            "height": 160,
            "color": "#fff"
          },
          {
            "type": "image",
            "x": 5,
            "y": 5,
            "width": 93,
            "height": 150,
            "dynamicProperties": {
              "color": "suitColor"
            },
            "css": "border-radius:7px"
          },
          {
            "type": "image",
            "x": 21.5,
            "y": 50,
            "width": 60,
            "height": 60,
            "color": "#fff",
            "css": "border-radius:100%; border:1px solid #444; background-size: 80%"
          },
          {
            "type": "icon",
            "x": 21.5,
            "y": 50,
            "size": 60,
            "scale": 0.8,
            "strokeColor": "#1f1f1f",
            "strokeWidth": 8,
            "dynamicProperties": {
              "value": "suit",
              "color": "suitColor"
            }
          },
          {
            "type": "text",
            "x": 10,
            "y": 10,
            "textAlign": "center",
            "width": 30,
            "height": 30,
            "fontSize": 25,
            "color": "black",
            "dynamicProperties": {
              "value": "rank"
            },
            "css": "font-weight: bold !important; display: flex;justify-content: center; align-items: center;text-align: center;  border:1px solid black; border-radius:5px; background-color: #fff; letter-spacing: -1px"
          },
          {
            "type": "text",
            "x": 63,
            "y": 120,
            "textAlign": "center",
            "width": 30,
            "height": 30,
            "fontSize": 25,
            "color": "black",
            "dynamicProperties": {
              "value": "rank"
            },
            "css": "font-weight: bold !important; display: flex;justify-content: center; align-items: center;text-align: center;  border:1px solid black; border-radius:5px; background-color: #fff; letter-spacing: -1px",
            "rotation": 0
          }
        ],
        "border": 1
      }
    ];
    return deck;
  }

  deckTemplate_simple(deck) {
    deck.cardDefaults = {
    };
    deck.faceTemplates = [
      {
        "objects": [
          {
            "type": "image",
            "width": 103,
            "height": 160,
            "color": "transparent",
            "value": "/i/cards-default/2B.svg"
          }
        ]
      },
      {
        "radius": 16,
        "objects": [
          {
            "type": "image",
            "width": 103,
            "height": 160,
            "dynamicProperties": {
              "color": "suitColor"
            }
          },
          {
            "type": "icon",
            "x": 10,
            "y": 70,
            "size": 83,
            "color": "#fff4",
            "strokeColor": "#fff4",
            "strokeWidth": 20,
            "dynamicProperties": {
              "value": "suit",
            }
          },
          {
            "type": "text",
            "y": 0,
            "fontSize": 60,
            "textAlign": "center",
            "color": "white",
            "width": 103,
            "dynamicProperties": {
              "value": "rank"
            }
          }
        ]
      }
    ];
    return deck;
  }

  deckTemplate_skinny(deck) {
    deck.cardDefaults = {
      width: 80,
      height: 160
    };
    deck.faceTemplates = [
      {
        "objects": [
          {
            "type": "image",
            "width": 80,
            "height": 160,
            "color": "transparent",
            "value": "/i/cards-skinny/1B.svg"
          }
        ]
      },
      {
        "objects": [
          {
            "type": "image",
            "width": 80,
            "height": 160,
            "color": "white"
          },
          {
            "type": "icon",
            "x": 10,
            "y": 80,
            "size": 60,
            "dynamicProperties": {
              "value": "suit",
              "color": "suitColor"
            }
          },
          {
            "type": "text",
            "y": 10,
            "fontSize": 60,
            "textAlign": "center",
            "width": 80,
            "dynamicProperties": {
              "color": "suitColor",
              "value": "rank"
            }
          }
        ]
      }
    ];
    return deck;
  }

  deckTemplate_transparent(deck) {
    deck.cardDefaults = {
      width: 80,
      height: 80
    };
    deck.faceTemplates = [
      {
        "objects": [
          {
            "type": "image",
            "width": 80,
            "height": 80,
            "color": "white",
            "value": "/i/cards-default/2B.svg"
          }
        ]
      },
      {
        "radius": 16,
        "objects": [
          {
            "type": "icon",
            "size": 80,
            "dynamicProperties": {
              "value": "suit",
              "color": "suitColor"
            }
          },
          {
            "type": "text",
            "y": 18,
            "fontSize": 40,
            "textAlign": "center",
            "color": "white",
            "width": 80,
            "dynamicProperties": {
              "value": "rank"
            }
          }
        ]
      }
    ];
    return deck;
  }

  deckTemplate_standard(deck) {
    deck.faceTemplates = [
      {
        "objects": [
          {
            "type": "image",
            "width": 103,
            "height": 160,
            "color": "transparent",
            "value": "/i/cards-default/2B.svg"
          }
        ]
      },
      {
        "border": 1,
        "radius": 6,
        "objects": [
          {
            "type": "image",
            "width": 103,
            "height": 160,
            "color": "white"
          },
          {
            "type": "image",
            "x": 25,
            "y": 25,
            "width": 53,
            "height": 110,
            "color": "white",
            "dynamicProperties": {
              "value": "rankImage"
            },
            "svgReplaces": {
              "#000": "suitColor"
            },
            "css": {
              "background-size": "100% 100%"
            }
          },
          {
            "type": "text",
            "x": -3,
            "y": -2,
            "fontSize": 30,
            "textAlign": "center",
            "width": 25,
            "dynamicProperties": {
              "value": "rank",
              "color": "suitColor"
            },
            "css": {
              "letter-spacing": "-6px"
            }
          },
          {
            "type": "text",
            "x": 81,
            "y": 127,
            "fontSize": 30,
            "textAlign": "center",
            "width": 25,
            "dynamicProperties": {
              "value": "rank",
              "color": "suitColor"
            },
            "rotation": 180,
            "css": {
              "letter-spacing": "-6px"
            }
          },
          {
            "type": "icon",
            "x": 1,
            "y": 28,
            "size": 23,
            "dynamicProperties": {
              "value": "suit",
              "color": "suitColor"
            }
          },
          {
            "type": "icon",
            "x": 79,
            "y": 110,
            "size": 23,
            "dynamicProperties": {
              "value": "suit",
              "color": "suitColor"
            },
            "rotation": 180
          }
        ]
      }
    ];

    const commonProperties = {
      type: 'icon',
      size: 16
    }
    for(let row = 0; row < 5; row++) {
      for(let col = 0; col < 3; col++) {
        const x = 25 + col * 18.5;
        const y = 25 + row * 23.5;
        deck.faceTemplates[1].objects.push(Object.assign({}, commonProperties, {
          x, y,
          dynamicProperties: {
            value: `suit-P${row + 1}${col + 1}`,
            color: 'suitColor'
          }
        }));
      }
    }

    for(let row = 0; row < 4; row++) {
      for(let col = 0; col < 3; col++) {
        const x = 25 + col * 18.5;
        const y = 40.6 + (row > 1 ? row + 1 : row) * 15.6;
        deck.faceTemplates[1].objects.push(Object.assign({}, commonProperties, {
          x, y,
          dynamicProperties: {
            value: `suit-S${row + 1}${col + 1}`,
            color: 'suitColor'
          }
        }));
      }
    }
    return deck;
  }

  faceObjectInputValueUpdated(deck, face, object, property, value, card, removeObjects) {
    if(typeof value === undefined)
      delete this.faceTemplates[face].objects[object][property];
    else
      this.faceTemplates[face].objects[object][property] = value;

    //card.applyDeltaToDOM({ deck: card.get('deck') });
    for(let objectCard=object; objectCard<this.cardLayerCards[face].length; ++objectCard) {
      const oCard = this.cardLayerCards[face][objectCard];
      oCard.domElement.innerHTML = '';
      oCard.createFaces(this.faceTemplates);
      for(let i=0; i<oCard.domElement.children.length; ++i)
        oCard.domElement.children[i].classList.toggle('active', i == oCard.get('activeFace'));
      removeObjects(oCard, objectCard);
    }
  }

  async applyFaceTemplateChanges(deck) {
    batchStart();
    setDeltaCause(`${getPlayerDetails().playerName} updated face templates of deck ${deck.id} in editor`);
    await deck.set('faceTemplates', JSON.parse(JSON.stringify(this.faceTemplates)));
    batchEnd();
  }

  renderCardLayers(deck) {
    const card = new Card();
    card.state.deck = deck.id;
    card.state.cardType = Object.keys(deck.get('cardTypes'))[0];
    const faceTemplates = this.faceTemplates = JSON.parse(JSON.stringify(deck.get('faceTemplates')));

    this.cardLayerCards = [];

    for(const face in faceTemplates) {
      this.cardLayerCards[face] = [];

      if(face == 0)
        this.addHeader('Back face');
      else if(face == 1)
        this.addHeader('Front face');
      else
        this.addHeader(`Face ${face}`);

      for(const object in faceTemplates[face].objects) {
        const objectDiv = document.createElement('div');
        objectDiv.className = 'faceTemplateEdit';

        const cardClone = this.cardLayerCards[face][object] = card.renderReadonlyCopy({ activeFace: face }, objectDiv);
        const removeObjects = function(card, object) {
          for(const objectDOM of $a(`.active.cardFace .cardFaceObject:nth-child(n+${+object+2})`, card.domElement))
            objectDOM.remove();
        };
        removeObjects(cardClone, object);
        const propsDiv = document.createElement('div');
        propsDiv.className = 'faceTemplateProperty';
        for(const prop in faceTemplates[face].objects[object])
          this.addInput(prop, faceTemplates[face].objects[object][prop], v=>this.faceObjectInputValueUpdated(deck, face, object, prop, v, card, removeObjects), propsDiv);
        objectDiv.appendChild(propsDiv);
        this.moduleDOM.appendChild(objectDiv);
      }
    }

    const applyButton = document.createElement('button');
    applyButton.innerText = 'Apply changes';
    applyButton.setAttribute('icon', 'check');
    applyButton.onclick = e=>this.applyFaceTemplateChanges(deck);
    this.moduleDOM.appendChild(applyButton);
  }

  renderCardTypes(deck, onlyCardType=null) {
    const card = new Card();
    card.state.deck = deck.id;
    card.deck = deck;
    const cardTypes = this.cardTypes = JSON.parse(JSON.stringify(deck.get('cardTypes')));

    this.cardTypeCards = [];

    for(const cardType in cardTypes) {
      if(onlyCardType !== null && onlyCardType != cardType)
        continue;

      const cardTypeDiv = div(this.moduleDOM, 'cardTypeEdit', `
        <div class=cardCountDiv>
          <button icon=remove></button>
          <button icon=add></button>
        </div>
        <div class=renderedWidget></div>
        <button icon=create>Edit</button>
        <div class=cardTypeProperties>
          <div></div>
          <div class=buttonBar>
            <button icon=close class=red>Discard changes</button>
            <button icon=check class=green>Apply changes</button>
          </div>
        </div>
      `);
      $('[icon=create]', cardTypeDiv).onclick = _=>this.renderCardTypes_editProperties(deck, cardType, cardTypeDiv);

      this.cardTypeCards[cardType] = [];

      const cardClone = new Card();
      const newState = {...card.state};
      newState.activeFace = card.getFaceCount()>1?1:0;
      newState.cardType = cardType;
      cardClone.renderReadonlyCopyRaw(newState, $('.renderedWidget', cardTypeDiv));

      this.cardTypeCards[cardType] = cardClone;

      let cardCount = widgetFilter(w => w.get('deck') == deck.id && w.get('cardType') == cardType).length;
      const input = this.addInput('Card Count', cardCount, v=>updateCount(0, v), $('.cardCountDiv', cardTypeDiv), 'number');

      function updateCount(delta, setValue) {
        // Parse the value, ensure it's non-negative
        cardCount = Math.max(0, (parseInt(typeof setValue === 'number' ? setValue : cardCount, 10)||0)+delta);
        input.setValue(cardCount);
        setCardCount(deck, cardType, cardCount);
      }

      this.addDeltaListener(delta => {
        for(const props of Object.values(delta))
          if(props === null || props.deck || props.cardType)
            return input.setValue(widgetFilter(w => w.get('deck') == deck.id && w.get('cardType') == cardType).length);
      });

      $('[icon=remove]', cardTypeDiv).onclick = e => updateCount(-1);
      $('[icon=add]', cardTypeDiv).onclick = e => updateCount(1);

      $('.cardCountDiv', cardTypeDiv).insertBefore($('input', input.dom), $('[icon=add]', cardTypeDiv));
      input.dom.remove();
    }
  }

  renderCardTypes_editProperties(deck, cardType, cardTypeDiv) {
    $('.cardTypeProperties > div', cardTypeDiv).innerHTML = '';
    cardTypeDiv.classList.add('cardCountDivEditing');

    const cardTypeProperties = JSON.parse(JSON.stringify(deck.get('cardTypes')))[cardType];

    const addPropertyInput = (property, value)=>{
      this.addInput(property, value, v=>{
        if(typeof v === undefined)
          delete cardTypeProperties[property];
        else
          cardTypeProperties[property] = v;
        this.renderCardTypes_updateCardVisualization(deck, cardType, { [property]: v });
      }, $('.cardTypeProperties > div', cardTypeDiv));
    };

    for(const [ property, value ] of Object.entries(cardTypeProperties))
      addPropertyInput(property, value);

    for(const face of deck.get('faceTemplates'))
      for(const object of face.objects || [])
        for(const prop of Object.values(object.dynamicProperties || {}))
          if(typeof cardTypeProperties[prop] === 'undefined' && [ 'cardType', 'id' ].indexOf(prop) == -1)
            addPropertyInput(prop, cardTypeProperties[prop]);

    $('[icon=check]', cardTypeDiv).onclick = async _=>{
      cardTypeDiv.classList.remove('cardCountDivEditing');

      batchStart();
      setDeltaCause(`${getPlayerDetails().playerName} updated card types of deck ${deck.id} in editor`);
      const cardTypes = JSON.parse(JSON.stringify(deck.get('cardTypes')));
      cardTypes[cardType] = cardTypeProperties;
      await deck.set('cardTypes', cardTypes);
      batchEnd();
    };

    $('[icon=close]', cardTypeDiv).onclick = _=>{
      cardTypeDiv.classList.remove('cardCountDivEditing');
      this.renderCardTypes_updateCardVisualization(deck, cardType, deck.get('cardTypes')[cardType]);
    };
  }

  renderCardTypes_updateCardVisualization(deck, cardType, changes) {
      const oCard = this.cardTypeCards[cardType];
      oCard.domElement.innerHTML = '';
      Object.assign(oCard.state, changes);
      oCard.createFaces(deck.get('faceTemplates'));
      for (let i = 0; i < oCard.domElement.children.length; ++i) {
          oCard.domElement.children[i].classList.toggle('active', i == oCard.get('activeFace'));
      }
  }

  // --- shared sections for the per-type editors ---

  renderInputs(widget, defs, target=null) {
    const kinds = {
      text: TextInput,
      textarea: TextInput,
      number: NumberInput,
      checkbox: CheckboxInput,
      select: SelectInput,
      color: ColorInput,
      icon: IconInput,
      image: ImageInput
    };
    for(const def of defs) {
      const options = Object.assign({}, def);
      if(def.kind == 'textarea')
        options.multiline = true;
      if(def.cssKey)
        Object.assign(options, cssValueOptions(this, widget, def.cssKey));
      new kinds[def.kind](this, widget, def.label, options).render(target || this.moduleDOM);
    }
  }

  renderTypeHeader(widget) {
    const type = widget.get('type') || 'basic';
    this.addHeader(`${editorTypeNames[type] || type} ${widget.id}`);
  }

  renderBasicSection(widget) {
    this.addSubHeader('Position and size');
    this.renderInputs(widget, [
      { label: 'X',        property: 'x',        kind: 'number', min: 0, max: 1600, step: 1, slider: true },
      { label: 'Y',        property: 'y',        kind: 'number', min: 0, max: 1000, step: 1, slider: true },
      { label: 'Width',    property: 'width',    kind: 'number', min: 1, max: 1600, step: 1, slider: true },
      { label: 'Height',   property: 'height',   kind: 'number', min: 1, max: 1000, step: 1, slider: true },
      { label: 'Rotation', property: 'rotation', kind: 'number', min: 0, max: 360, step: 1, slider: true },
      { label: 'Layer',    property: 'layer',    kind: 'select', choices: [
        { value: -5, text: '-5 (background)' },
        { value: -4, text: '-4' },
        { value: -3, text: '-3 (holders)' },
        { value: -2, text: '-2 (labels)' },
        { value: -1, text: '-1 (buttons, seats, timers)' },
        { value:  0, text: '0' },
        { value:  1, text: '1 (cards, dice, pieces)' },
        { value:  2, text: '2' },
        { value:  3, text: '3' },
        { value:  4, text: '4' },
        { value:  5, text: '5' }
      ] },
      { label: 'Movable by players',   property: 'movable',       kind: 'checkbox' },
      { label: 'Movable in edit mode', property: 'movableInEdit', kind: 'checkbox' }
    ]);
  }

  typeSectionProperties(type) {
    const sections = editorTypeSections[type] || {};
    const properties = [];
    for(const defs of [ sections.appearance || [], sections.behavior || [] ])
      for(const def of defs)
        properties.push(def.property || 'css');
    return properties;
  }

  basicExcludeList(widget, extra=[]) {
    return [ 'x', 'y', 'z', 'width', 'height', 'rotation', 'layer', 'movable', 'movableInEdit' ]
      .concat(this.typeSectionProperties(widget.get('type') || 'basic'))
      .concat(extra);
  }

  // Appearance section with a pipette button (copy the appearance from a
  // picked widget) and a button to apply the appearance to all widgets of
  // the same type.
  renderAppearanceSection(widget, options={}) {
    const type = widget.get('type') || 'basic';
    const defs = options.defs !== undefined ? options.defs : ((editorTypeSections[type] || {}).appearance || []);
    if(!defs.length && !options.render)
      return;
    const properties = options.properties || [...new Set(defs.map(d=>d.property || 'css'))];

    const copyProperties = async (source, target)=>{
      for(const property of properties)
        await target.set(property, source.state[property] !== undefined ? JSON.parse(JSON.stringify(source.state[property])) : null);
    };

    const header = div(this.moduleDOM, 'sectionHeaderWithTools', `
      <h2>Appearance</h2>
      <button icon=palette class=pickAppearance title="Pick appearance from another widget: click this button and then the widget to copy from."></button>
      <button icon=content_copy class=applyAppearanceToAll title="Apply this appearance to all widgets of this type."></button>
    `);

    $('.pickAppearance', header).onclick = e=>{
      if(this.widgetPick) {
        this.stopWidgetPick();
        $('.pickAppearance', header).classList.remove('selected');
        return;
      }
      $('.pickAppearance', header).classList.add('selected');
      this.startWidgetPick(widget, async source=>{
        batchStart();
        setDeltaCause(`${getPlayerDetails().playerName} copied appearance from widget ${source.id} to ${widget.id} in editor`);
        await copyProperties(source, widget);
        batchEnd();
      });
    };

    $('.applyAppearanceToAll', header).onclick = async _=>{
      batchStart();
      setDeltaCause(`${getPlayerDetails().playerName} applied appearance of widget ${widget.id} to all ${type} widgets in editor`);
      for(const other of widgetFilter(w=>(w.get('type') || 'basic') == type && w.id != widget.id))
        await copyProperties(widget, other);
      batchEnd();
    };

    if(options.render)
      options.render(this.moduleDOM);
    else
      this.renderInputs(widget, defs);
  }

  renderBehaviorSection(widget, title='Behavior') {
    const defs = (editorTypeSections[widget.get('type') || 'basic'] || {}).behavior || [];
    if(!defs.length)
      return;
    this.addSubHeader(title);
    this.renderInputs(widget, defs);
  }

  renderOtherPropertiesSection(widget, extraExclude=[]) {
    this.addSubHeader('Other properties');
    this.renderGenericProperties(widget, this.basicExcludeList(widget, extraExclude));
  }

  // --- per-type editors ---

  renderForBasic(widget) {
    this.renderTypeHeader(widget);
    this.renderBasicSection(widget);
    this.renderAppearanceSection(widget);
    this.renderOtherPropertiesSection(widget);
  }

  renderForButton(widget) {
    this.renderTypeHeader(widget);
    this.renderBasicSection(widget);
    this.renderAppearanceSection(widget);
    this.addSubHeader('Behavior');
    div(this.moduleDOM, '', `
      <p>What the button does when clicked is defined by its <b>clickRoutine</b> which you can edit in the JSON editor.</p>
    `);
    this.renderOtherPropertiesSection(widget);
  }

  renderForCanvas(widget) {
    this.renderTypeHeader(widget);
    this.renderBasicSection(widget);
    this.renderAppearanceSection(widget, {
      properties: [ 'colorMap' ],
      render: target=>{
        const colorMap = asArray(widget.get('colorMap') || []);
        for(let i=0; i<colorMap.length; ++i) {
          new ColorInput(this, widget, `Color ${i}`, {
            clearable: false,
            listenTo: [ 'colorMap' ],
            getValue: _=>{
              const map = asArray(widget.get('colorMap') || []);
              return map[i] !== undefined ? map[i] : null;
            },
            setValue: v=>{
              const map = asArray(widget.get('colorMap') || []).slice();
              map[i] = v === null ? '#000000' : v;
              this.inputValueUpdated(widget, 'colorMap', map);
            }
          }).render(target);
        }
      }
    });
    this.renderBehaviorSection(widget, 'Drawing');
    this.renderOtherPropertiesSection(widget, [ 'colorMap' ]);
  }

  renderForLabel(widget) {
    this.renderTypeHeader(widget);
    this.renderBasicSection(widget);

    this.addSubHeader('Label');
    this.renderInputs(widget, [
      { label: 'Text',                     property: 'text',            kind: 'textarea' },
      { label: 'Editable by players',      property: 'editable',        kind: 'checkbox' },
      { label: 'Placeholder when empty',   property: 'placeholderText', kind: 'text', nullIfEmpty: true }
    ]);

    this.renderAppearanceSection(widget, {
      properties: [ 'css' ],
      render: target=>{
        const row = div(target, 'propertyTypographyRow');
        new CssToggleButton(this, widget, null, cssValueOptions(this, widget, 'font-weight', { icon: 'format_bold',         onValue: 'bold',   tooltip: 'Bold' })).render(row);
        new CssToggleButton(this, widget, null, cssValueOptions(this, widget, 'font-style',  { icon: 'format_italic',       onValue: 'italic', tooltip: 'Italic' })).render(row);
        new CssToggleButton(this, widget, null, cssValueOptions(this, widget, 'text-align',  { icon: 'format_align_left',   onValue: 'left',   tooltip: 'Align left' })).render(row);
        new CssToggleButton(this, widget, null, cssValueOptions(this, widget, 'text-align',  { icon: 'format_align_center', onValue: 'center', tooltip: 'Align center' })).render(row);
        new CssToggleButton(this, widget, null, cssValueOptions(this, widget, 'text-align',  { icon: 'format_align_right',  onValue: 'right',  tooltip: 'Align right' })).render(row);
        new NumberInput(this, widget, 'Font size', cssNumberOptions(this, widget, 'font-size', { min: 6, max: 150, step: 1, slider: true, nullIfEmpty: true, unit: 'px' })).render(target);
        new ColorInput(this, widget, 'Text color', cssValueOptions(this, widget, 'color')).render(target);
      }
    });

    this.renderOtherPropertiesSection(widget, [ 'text', 'editable', 'placeholderText', 'css' ]);
  }

  renderForPile(widget) {
    this.renderTypeHeader(widget);
    this.renderBasicSection(widget);
    this.renderAppearanceSection(widget);
    this.renderBehaviorSection(widget);
    this.renderOtherPropertiesSection(widget);
  }

  renderForScoreboard(widget) {
    this.renderTypeHeader(widget);
    this.renderBasicSection(widget);
    this.renderAppearanceSection(widget);
    this.renderBehaviorSection(widget, 'Scores');
    this.renderOtherPropertiesSection(widget);
  }

  renderForSeat(widget) {
    this.renderTypeHeader(widget);
    this.renderBasicSection(widget);
    this.renderAppearanceSection(widget);
    this.renderBehaviorSection(widget, 'Seat');
    this.renderOtherPropertiesSection(widget);
  }

  renderForTimer(widget) {
    this.renderTypeHeader(widget);
    this.renderBasicSection(widget);
    this.renderAppearanceSection(widget);
    this.renderBehaviorSection(widget, 'Timer');
    this.renderOtherPropertiesSection(widget);
  }

  renderForCard(widget) {
    this.addHeader(`Card ${widget.id}`);
    this.renderBasicSection(widget);
    this.addSubHeader(`Card properties`);
    this.renderGenericProperties(widget, this.basicExcludeList(widget, [ 'deck' ]));
    this.addSubHeader(`Card type`);
    this.renderCardTypes(widgets.get(widget.get('deck')), widget.get('cardType'));
    div(this.moduleDOM, '', `
      <p>Open the deck of this card to edit what card types exist and how the cards look like.</p>
      <div class=buttonBar>
        <button icon=style>Open deck</button>
      </div>
    `);
    $('[icon=style]', this.moduleDOM).onclick = _=>setSelection([ widgets.get(widget.get('deck')) ]);
  }

  renderForDeck(widget) {
    this.addHeader(`Deck ${widget.id}`);
    this.renderBasicSection(widget);
    this.addSubHeader(`Card types`);
    div(this.moduleDOM, 'buttonBar', `
      <button icon=remove class=removeAll>All</button>
      <button icon=add class=addAll>All</button>
    `);
    this.renderCardTypes(widget);
    $('.removeAll', this.moduleDOM).onclick = async _=>{
      batchStart();
      setDeltaCause(`${getPlayerDetails().playerName} removed one card of each type from deck ${widget.id} in editor`);
      for(const cardType in widget.get('cardTypes')) {
        const cards = widgetFilter(w=>w.get('deck')==widget.id&&w.get('cardType')==cardType);
        if(cards.length)
          await setCardCount(widget, cardType, cards.length - 1);
      }
      batchEnd();
    };
    $('.addAll', this.moduleDOM).onclick = async _=>{
      batchStart();
      setDeltaCause(`${getPlayerDetails().playerName} added one card of each type to deck ${widget.id} in editor`);
      for(const cardType in widget.get('cardTypes')) {
        const cards = widgetFilter(w=>w.get('deck')==widget.id&&w.get('cardType')==cardType);
        await setCardCount(widget, cardType, cards.length + 1);
      }
      batchEnd();
    };

    this.addSubHeader(`Card layers`);
    if(Object.values(widget.get('cardTypes')).length)
      this.renderCardLayers(widget);
    else
      div(this.moduleDOM, '', `<p>Please add a cardType first.</p>`);

    this.addSubHeader(`Card default properties`);
    for(const [ prop, value ] of Object.entries(widget.get('cardDefaults'))) {
      this.addInput(prop, value, v=>{
        const defaults = JSON.parse(JSON.stringify(widget.get('cardDefaults')));
        defaults[prop] = v;
        widget.set('cardDefaults', defaults);
      });
    }

    this.addSubHeader(`Deck properties`);
    div(this.moduleDOM, '', `
      <p>These are properties acting on the deck widget itself which has no influence on gameplay. These properties do not apply to the cards. Which is why this section is usually empty.</p>
    `);
    this.renderGenericProperties(widget, this.basicExcludeList(widget, [ 'cardTypes', 'faceTemplates', 'cardDefaults' ]));
  }

  renderForDice(widget) {
    this.addHeader(`Dice ${widget.id}`);
    this.renderBasicSection(widget);
    const widgetFaces = widget.get('faces');
    const faceCount = Array.isArray(widgetFaces) ? widgetFaces.length : 0;

    this.addSubHeader('Dice types');
    const faces = [
      ["H", "T"],
      [1, 2, 3, 4],
      [1, 2, 3, 4, 5, 6],
      [1, 2, 3, 4, 5, 6, 7, 8],
      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    ];

    for (const f of faces) {
      const dice = this.renderWidgetButton(new Dice(), {
        type: 'dice',
        faces: f,
        activeFace: f.length - 1,
        shape3d: widget.get('shape3d'),
        pipSymbols: widget.get('pipSymbols')
      }, this.moduleDOM);

      this.addPropertyListener(widget, 'faces', widget => {
        if (JSON.stringify(widgetFaces) === JSON.stringify(f)) {
          dice.classList.add('selected');
        } else {
          dice.classList.remove('selected');
        }
      });
      dice.onclick = async e => {
        if (!dice.classList.contains('selected')) {
          widget.set('faces', f);
        }
      };
    }

    this.addSubHeader('Dice shape');
    const shape = [true, false];

    for (const s of shape) {
      const diceShape = this.renderWidgetButton(new Dice(), {
        type: 'dice',
        faces: widgetFaces,
        activeFace: faceCount - 1,
        shape3d: s,
        pipSymbols: widget.get('pipSymbols')
      }, this.moduleDOM);

      this.addPropertyListener(widget, 'shape3d', widget => {
        if (JSON.stringify(widget.get('shape3d')) === JSON.stringify(s)) {
          diceShape.classList.add('selected');
        } else {
          diceShape.classList.remove('selected');
        }
      });

      diceShape.onclick = async e => {
        if (!diceShape.classList.contains('selected')) {
          widget.set('shape3d', s);
        }
      };
    }

    this.addSubHeader('Face type');
    const pipType = [true, false];

    for (const p of pipType) {
      const dicePip = this.renderWidgetButton(new Dice(), {
        type: 'dice',
        faces: widgetFaces,
        activeFace: faceCount - 1,
        shape3d: widget.get('shape3d'),
        pipSymbols: p
      }, this.moduleDOM);

      this.addPropertyListener(widget, 'pipSymbols', widget => {
        if (JSON.stringify(widget.get('pipSymbols')) === JSON.stringify(p)) {
          dicePip.classList.add('selected');
        } else {
          dicePip.classList.remove('selected');
        }
      });

      dicePip.onclick = async e => {
        if (!dicePip.classList.contains('selected')) {
          widget.set('pipSymbols', p);
        }
      };
    }

    this.renderAppearanceSection(widget);
    this.renderBehaviorSection(widget, 'Rolling');

    this.addSubHeader(`Dice properties`);
    this.renderGenericProperties(widget, this.basicExcludeList(widget, [ 'faces', 'pipSymbols', 'shape3d' ]));
  }

  renderForHolder(widget) {
    this.addHeader(`Holder ${widget.id}`);
    this.renderBasicSection(widget);
    this.addSubHeader('Target widgets');
    for(const deck of widgetFilter(w=>w.get('type') == 'deck')) {
      if(!Object.keys(deck.get('cardTypes')).length)
        continue;
      const deckCloneState = Object.assign({}, deck.state, { id: generateUniqueWidgetID() });
      const deckButton = this.renderWidgetButton(new Deck(deckCloneState.id), deckCloneState, this.moduleDOM);
      this.addPropertyListener(widget, 'dropTarget', widget=>{
        if(asArray(widget.get('dropTarget')).filter(t=>t.deck == deck.id).length)
          deckButton.classList.add('selected');
        else
          deckButton.classList.remove('selected');
      });
      deckButton.onclick = async e=>{
        let newDropTarget = asArray(widget.get('dropTarget'));
        if(deckButton.classList.contains('selected'))
          newDropTarget = newDropTarget.filter(t=>t.deck != deck.id);
        else
          newDropTarget = newDropTarget.filter(t=>t.type!='card').concat({ deck: deck.id });

        if(newDropTarget.length == 1)
          newDropTarget = newDropTarget[0];
        else if(!newDropTarget.length)
          newDropTarget = null;

        widget.set('dropTarget', newDropTarget);
      };
    }


    this.renderAppearanceSection(widget, {
      properties: [ 'color', 'textColor', 'borderRadius', 'dropShadow', 'image', 'css', 'classes' ],
      render: _=>{}
    });
    const normal = this.renderWidgetButton(new Holder(), {
      type: 'holder',
      width: 50,
      height: 70
    }, this.moduleDOM);
    const semi = this.renderWidgetButton(new Holder(), {
      type: 'holder',
      width: 50,
      height: 70,
      css: { background: '#fff6' }
    }, this.moduleDOM);
    const transparent = this.renderWidgetButton(new Holder(), {
      type: 'holder',
      width: 50,
      height: 70,
      classes: 'transparent'
    }, this.moduleDOM);

    this.addPropertyListener(widget, 'css', widget=>{
      if(!widget.get('css') && !widget.get('classes'))
        normal.classList.add('selected');
      else
        normal.classList.remove('selected');
    });
    this.addPropertyListener(widget, 'classes', widget=>{
      if(!widget.get('css') && !widget.get('classes'))
        normal.classList.add('selected');
      else
        normal.classList.remove('selected');
    });
    normal.onclick = async e=>{
      if(!normal.classList.contains('selected')) {
        widget.set('classes', null);
        widget.set('css', null);
      }
    };

    this.addPropertyListener(widget, 'css', widget=>{
      if(String(widget.get('css')).includes('#fff6'))
        semi.classList.add('selected');
      else
        semi.classList.remove('selected');
    });
    semi.onclick = e=>{
      if(!semi.classList.contains('selected')) {
        widget.set('classes', null);
        widget.set('css', 'background:#fff6');
      }
    };

    this.addPropertyListener(widget, 'classes', widget=>{
      if(String(widget.get('classes')).includes('transparent'))
        transparent.classList.add('selected');
      else
        transparent.classList.remove('selected');
    });
    transparent.onclick = e=>{
      if(!transparent.classList.contains('selected')) {
        widget.set('classes', 'transparent');
        widget.set('css', null);
      }
    };
    this.renderInputs(widget, editorTypeSections.holder.appearance);

    this.renderBehaviorSection(widget, 'Dropping and stacking');

    this.addSubHeader(`Holder properties`);
    this.renderGenericProperties(widget, this.basicExcludeList(widget, [ 'dropTarget', 'css', 'classes' ]));
  }

  renderForSpinner(widget) {
    this.addHeader(`Spinner ${widget.id}`);
    this.renderBasicSection(widget);

    this.addSubHeader('Spinner Options');
    const options = [
      ["H", "T"],
      [1, 2, 3],
      [1, 2, 3, 4],
      [1, 2, 3, 4, 5, 6],
      [1, 2, 3, 4, 5, 6, 7, 8],
      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    ];

    for (const option of options) {
      const spinner = this.renderWidgetButton(new Spinner(), {
        type: 'spinner',
        options: option
      }, this.moduleDOM);

      this.addPropertyListener(widget, 'options', widget => {
        if (JSON.stringify(widget.get('options')) === JSON.stringify(option)) {
          spinner.classList.add('selected');
        } else {
          spinner.classList.remove('selected');
        }
      });

      spinner.onclick = async e => {
        if (!spinner.classList.contains('selected')) {
          widget.set('options', option);
        }
      };
    }

    this.renderAppearanceSection(widget);
    this.renderBehaviorSection(widget, 'Value');

    this.addSubHeader(`Spinner properties`);
    this.renderGenericProperties(widget, this.basicExcludeList(widget, [ 'options' ]));
  }

  renderGenericProperties(widget, exclude) {
    for(const property in widget.state) {
      if([ 'id', 'type', 'parent' ].concat(exclude).indexOf(property) != -1)
        continue;

      const input = this.addInput(property, widget.state[property], v=>this.inputValueUpdated(widget, property, v))
      if(!this.inputUpdaters[widget.id][property])
        this.inputUpdaters[widget.id][property] = [];

      this.inputUpdaters[widget.id][property].push(input.setValue);
    }
  }

  renderWidgetButton(widget, state, target) {
    const button = document.createElement('button');
    button.className = 'widgetSelectionButton';
    target.appendChild(button);

    let deckDOM = null;
    if(widget instanceof Deck && widget.get('type') != 'deck')
      deckDOM = widget.renderReadonlyCopyRaw(state, button).domElement;

    if(widget.get('type') == 'deck') {
      const parent = new BasicWidget().renderReadonlyCopyRaw({}, button).domElement;
      const faceTemplates = widget.get('faceTemplates');
      widgets.set(widget.id, widget);
      for(const cardType of shuffleArray(Object.keys(widget.get('cardTypes'))).slice(0, 5)) {
        new Card().renderReadonlyCopyRaw(Object.assign({
          deck: widget.id,
          cardType,
          activeFace: Array.isArray(faceTemplates) && faceTemplates.length > 1 ? 1 : 0
        }, state), parent);
      }
      widgets.delete(widget.id, widget);
      if (parent.children[0]) 
        positionElementsInArc(parent.children, parent.children[0].clientHeight, 45, parent);
    } else {
      widget.renderReadonlyCopyRaw(state, button);
    }

    if(deckDOM)
      deckDOM.remove();

    const rect = getBoundingClientRectWithAbsoluteChildren(button.children[0]);
    if(Math.max(rect.width, rect.height) > 140)
      button.children[0].style.transform = `scale(${140/Math.max(rect.width, rect.height)})`;
    centerElementInClientRect(button.children[0], button.getBoundingClientRect());

    return button;
  }

  renderModule(target) {
    target.innerText = 'Properties module not implemented yet.';
  }
}
