#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const libraryPath = path.join(__dirname, '..', 'library', 'games');

function hasAIImagery(attribution) {
  if (!attribution) return false;
  const lower = attribution.toLowerCase();
  return lower.includes('midjourney') ||
         lower.includes('chatgpt') ||
         lower.includes('dall-e') ||
         lower.includes('stable diffusion') ||
         lower.includes('artificial intelligence') ||
         lower.includes('ai generated') ||
         lower.includes('generated by') && (lower.includes('ai') || lower.includes('chatgpt') || lower.includes('midjourney')) ||
         lower.includes('gemini ai') ||
         lower.includes('myninja');
}

function processGameFile(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const game = JSON.parse(content);
    
    if (!game._meta || !game._meta.info) {
      return false;
    }
    
    const info = game._meta.info;
    const hasAI = hasAIImagery(info.attribution);
    
    if (hasAI && !info.usesAIImagery) {
      info.usesAIImagery = true;
      fs.writeFileSync(filePath, JSON.stringify(game, null, 2) + '\n', 'utf8');
      return true;
    }
    
    return false;
  } catch (error) {
    console.error(`Error processing ${filePath}:`, error.message);
    return false;
  }
}

function scanDirectory(dir) {
  let updated = 0;
  
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    
    if (entry.isDirectory()) {
      updated += scanDirectory(fullPath);
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      if (processGameFile(fullPath)) {
        updated++;
        console.log(`Updated: ${fullPath}`);
      }
    }
  }
  
  return updated;
}

console.log('Scanning library games for AI-generated imagery...');
const updated = scanDirectory(libraryPath);
console.log(`\nDone! Updated ${updated} game file(s).`);
