import { ClientFunction, Selector } from 'testcafe';

import { compareState, prepareClient, setName, setRoomState, setupTestEnvironment } from './test-util.js';

setupTestEnvironment();

test('Create game using edit mode', async t => {
  const [width,height] = await t.eval(() => [window.innerWidth,window.innerHeight]);
  if(width<=960||height<=520)
    await t.resizeWindow(width>960?width:980,height>520?height:540);
  await setRoomState();
  await ClientFunction(prepareClient)();
  await setName(t);
  await t
    .click('#editButton')
    .pressKey('a')
    .pressKey('a')
    .click('#add-spinner0')
    .typeText('#INPUT_\\;values', '1')
    .pressKey('backspace')
    .pressKey('backspace')
    .pressKey('8')
    .click('#buttonInputGo')
    .rightClick('#w_2ng4')
    .pressKey('a')
    .click('#add-holder')
    .pressKey('a')
    .click('#addHand')
    .drag('#w_hand', 100, -100) // this shouldn't change anything because it's not movable
    .rightClick('#w_hand')
    .pressKey('a')
    .click('#add-deck_K_S')
    .pressKey('esc')
    .click('#w_9ee9B')
    .click('#w_9ee9P > .handle')
    .click('#pileOverlay .modal > div:nth-of-type(6) > button')
    .click('#w_b86p > .handle')
    .click('#pileOverlay .modal > div:nth-of-type(3) > button')
    .click('#w_b86p > .handle')
    .click('#pileOverlay .modal > div:nth-of-type(6) > button')
    .click('#w_5ip4 > .handle')
    .click('#pileOverlay .modal > div:nth-of-type(4) > button')
    .dragToElement('#w_5ip4 > .handle', '#w_hand')
    .pressKey('esc')
    .pressKey('esc')
    .click('#editButton')
    .click(Selector('button').withAttribute('icon', 'data_object'))
    .click('#w_2ng4')
    // This is temporarily removed because of the problem in the next line: .click('#je_duplicateWidget')
    // This does not work because there is nothing associated with the Go button that testCafe can find:  .click(Selector('button').withText('Go'))
    .click('#w_2ng4')
    .setNativeDialogHandler(() => true)
    .pressKey('d')
    .pressKey('esc')
    .pressKey('esc')
    .click('#editButton')
    .pressKey('a')
    .click('#add-2D-chips')
    .pressKey('esc')
    .click('#editButton')
    .pressKey('a')
    .click('#EmptyPoker3DSVG')
    .rightClick('#w_es5bB')
    .pressKey('esc')
    .click('#editButton')
    .pressKey('a')
    .click('#addSeat')
    .rightClick('#w_cgp8')
    .pressKey('esc')
    .click('#editButton')
    .pressKey('a')
    .click('#addSeatCounter')
    .rightClick('#w_m06r')
    .pressKey('esc')
    .click('#editButton')
    .pressKey('a')
    .click('#addScoreboard')
    .rightClick('#w_qz2l')
    .pressKey('esc')
    .click('#editButton')
    .pressKey('a')
    .click('#add-dice2D0')
    .typeText('#INPUT_\\;sides', '8', { replace: true })
    .click('#buttonInputGo')
    .rightClick('#w_8sfj')
    .pressKey('esc')
    .click('#editButton')
    .pressKey('a')
    .click('#add-dice3D0')
    .typeText('#INPUT_\\;sides', '12', { replace: true })
    .click('#buttonInputGo')
    .rightClick('#w_bldn')
    .click('#w_bldn')
    .drag(Selector('button').withAttribute('icon', 'drag_indicator'), -100, 100)
    .drag(Selector('button').withAttribute('icon', 'content_copy'), 100, 100)
    .drag(Selector('button').withAttribute('icon', 'format_line_spacing'), 100, 100)
    .drag(Selector('button').withAttribute('icon', 'settings_backup_restore'), -100, 0)
    .drag(Selector('button').withAttribute('icon', 'control_camera'), -500, -200)
  await t.resizeWindow(width,height);
  await compareState(t, '0409884b9427545b8e4b8ff77043a8a4');
});
