name: TestCafe Chrome (loads games, clicks buttons, checks the results)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Start virtualtabletop server
      run: |
        npm run debug &
        sleep 5
        curl -I http://localhost:8272
    - name: Run TestCafe tests
      uses: DevExpress/testcafe-action@latest
      with:
        version: "3.5.0"
        args: "chrome:headless tests/testcafe"
